// app/lib/plans.js

const plans = {
  cars: {
    Silver: {
      old: "$56.99",
      price: "$49.99",
      features: [
        "Vehicle Overview",
        "Market Value",
        "Vehicle Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
      ],
    },
    Gold: {
      old: "$119.99",
      price: "$89.99",
      features: [
        "HQ Car Images",
        "Vehicle Overview",
        "Market Value",
        "Vehicle Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
        "Title Record",
        "Impounds",
        "Exports",
        "Open Recalls",
        "Installed Options and Packages",
        "Active/Expire Warranty",
      ],
    },
    Platinum: {
      old: "$149.99",
      price: "$119.99",
      features: [
        "2 Buyers Numbers from our Directory",
        "Buy one get another Report Free for Lifetime",
        "HQ Car Images",
        "Vehicle Overview",
        "Market Value",
        "Vehicle Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
        "Title Record",
        "Impounds",
        "Exports",
        "Open Recalls",
        "Installed Options and Packages",
        "Active/Expire Warranty",
      ],
    },
  },
  motorbikes: {
    Silver: {
      old: "$56.99",
      price: "$49.99",
      features: [
        "Bike Overview",
        "Market Value",
        "Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
      ],
    },
    Gold: {
      old: "$119.99",
      price: "$89.99",
      features: [
        "HQ Bike Images",
        "Bike Overview",
        "Market Value",
        "Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
        "Title Record",
        "Impounds",
        "Exports",
        "Open Recalls",
        "Installed Options and Packages",
        "Active/Expire Warranty",
      ],
    },
    Platinum: {
      old: "$149.99",
      price: "$119.99",
      features: [
        "2 Buyers Numbers from our Directory",
        "Buy one get another Report Free for Lifetime",
        "HQ Bike Images",
        "Bike Overview",
        "Market Value",
        "Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
        "Title Record",
        "Impounds",
        "Exports",
        "Open Recalls",
        "Installed Options and Packages",
        "Active/Expire Warranty",
      ],
    },
  },
  rv: {
    Silver: {
      old: "$56.99",
      price: "$49.99",
      features: [
        "RV Overview",
        "Market Value",
        "Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
      ],
    },
    Gold: {
      old: "$119.99",
      price: "$89.99",
      features: [
        "HQ RV Images",
        "RV Overview",
        "Market Value",
        "Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
        "Title Record",
        "Impounds",
        "Exports",
        "Open Recalls",
        "Installed Options and Packages",
        "Active/Expire Warranty",
      ],
    },
    Platinum: {
      old: "$149.99",
      price: "$119.99",
      features: [
        "2 Buyers Numbers from our Directory",
        "Buy one get another Report Free for Lifetime",
        "HQ RV Images",
        "RV Overview",
        "Market Value",
        "Specifications",
        "Sales Listing",
        "Accident Record",
        "Salvage",
        "Theft Record",
        "Title Record",
        "Impounds",
        "Exports",
        "Open Recalls",
        "Installed Options and Packages",
        "Active/Expire Warranty",
      ],
    },
  },
};

export default plans;
